### ISSUE TITLE
Imagem só deve ser gerada após o merge para develop, release ou main 

### ISSUE THREAD

**Issue by vittooh** [AlexSnider/Aquila-Project#22]
Objetivo: Criar Workflows no GitHub Actions

Workflow para Testes:

Criar um arquivo de workflow que execute testes unitários e integrados ao abrir um Pull Request (PR) nas branches:
develop
main
release
staging
Workflow para Geração de Container:

Criar um segundo workflow que seja acionado ao realizar o merge nas branches:
develop
main
release
staging
Este workflow deve importar o primeiro workflow de testes.
Antes de gerar o container, rodar os testes:
Se os testes passarem, então gerar o container.

**Comment by AlexSnider** [comment]
Corrigido!
